In [1]:
import numpy as np

In [5]:
# Creating numpy array using lists
mylist = [1,2,3]
arr = np.array(mylist)

In [6]:
type(mylist)

list

In [7]:
type(arr)

numpy.ndarray

In [8]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
arr = np.array(mylist)

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr.shape

(3, 3)

In [17]:
# Range and step
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
# These are floating type majors
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.ones((5,5)) +4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [24]:
np.ones((5,5)) *100

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [31]:
# Range and number of equally spaced numbers we want
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
# gets 3 random number in between 0 and 1
np.random.rand(3,3)

array([[0.4884355 , 0.43179372, 0.65804906],
       [0.01228075, 0.32673139, 0.66221843],
       [0.63249657, 0.14210564, 0.27300879]])

In [39]:
# Getting random number normally distributed around zero
np.random.randn(3)

array([-1.45355775,  1.70206763,  0.18501604])

In [45]:
np.random.randint(0,100,10)

array([54, 22,  8, 70, 44, 30, 62, 98,  9, 93])

In [47]:
# Always getting the same number
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [53]:
arr = np.arange(25)

In [54]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
arr.max()

24

In [57]:
arr.min()

0

In [58]:
# Returning index location
arr.argmax()

24

In [59]:
arr.argmin()

0

In [61]:
array = np.arange(1,11)

In [62]:
# array indexing
array[8]

9

In [64]:
# array slicing
array[0:5]

array([1, 2, 3, 4, 5])

In [65]:
array[:5]

array([1, 2, 3, 4, 5])

In [66]:
# indexing on a 2d array

In [69]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [70]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arr2d[1][1]

5

In [73]:
arr2d[1,1]

5

In [75]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [76]:
arr >5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [77]:
bool_array = arr >10

In [78]:
bool_array

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [79]:
arr[arr > 6]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24])

In [80]:
arr[arr < 16]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [81]:
# Numpy operations

In [82]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [83]:
1/arr

<ipython-input-83-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158,
       0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667])

In [84]:
arr/arr

<ipython-input-84-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [85]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [86]:
np.log(arr)

<ipython-input-86-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [87]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836])

In [88]:
arr.sum()

300

In [91]:
arr.mean()

12.0

In [94]:
arr2d.sum(axis = 0)

array([12, 15, 18])

In [95]:
arr2d.sum(axis=1)

array([ 6, 15, 24])